package com.student.service;

import java.util.UUID;

import org.springframework.stereotype.Service;

import com.student.Student;

@Service
public class StudentService {

	public void createStudent(Student student) {
		
		
	}

	public Student getStudentById(String id) {
		String firstName = "Vishal";
        String lastName = "Jaiswal";

        String autoGeneratedId = generateId(firstName, lastName);
        System.out.println("Auto-generated ID: " + autoGeneratedId);
		return null;
	}

	private String generateId(String firstName, String lastName) {
		if (firstName.length() < 3 || lastName.length() < 3) {
            throw new IllegalArgumentException("First and last names must be at least 3 characters long.");
        }
		
		String uniqueId = UUID.randomUUID().toString();
        String id = firstName.substring(0, 3).toUpperCase() +
                    lastName.substring(0, 3).toUpperCase() +
                    uniqueId.substring(uniqueId.length() - 3);
		return id;
	}

}
